### ISSUE TITLE
Architecture trimming should be mentioned in README and on the webpage

### ISSUE THREAD

**Issue by Artoria2e5** [IngmarStein/Monolingual#233]
Now that fat binaries are becoming common again, it makes a lot of sense to really mention this feature.

**Comment by porg** [comment]
+1 I also came to the Monolingual website in the hopes for a M1/Intel fat binary trimming solution and looked for that info.

**Comment by porg** [comment]
Btw, is Monolingual suited for trimming the M1 or Intel part of fat binaries?
And if so, is this a manual oneshot operation?
Or a semi/fully automatic solution that runs event-based (filesystem changes in `/Applications/*`or AppStore events or PKG installer events) or schedule-based ( `every X min/hour/days` )?

**Comment by IngmarStein** [comment]
I don't have an M1-based Mac to test, so I would appreciated if someone could test https://github.com/IngmarStein/Monolingual/commit/22283e37c1e63869ff70ea39774ae70306a34b11 as provide feedback here.

As for oneshot vs. automated operation: Monolingual is currently a manual operation, but you may have some luck automating it using the embedded command-line interface provided by the helper tool, see
`/Applications/Monolingual.app/Contents/XPCServices/Monolingual.xpc/Contents/Library/LaunchServices/com.github.IngmarStein.Monolingual.Helper -h`

**Comment by porg** [comment]
Thanks for clarifying that stripping is currently a oneshot operation.

**Comment by porg** [comment]
Another inquiry: I would like to know "How much potential saving would I gain when stripping all or certain apps and certain architectures and languages?" **before** performing this. To consider whether the storage gain is worth the flexibility/portability loss. Does the app already do that?

**Mockup:**

⊟▾| Name | Current size | - architectures | - languages | Total saved | in %
-- | -- | -- | -- | -- | -- | -- 
☐| BBEdit | 23 MB | - 0,3 MB | - 2 MB | -2,3 MB | -10 %
☑︎| mpv | 80 MB | - 10 MB | - 10 MB | - 20 MB | -25 %
☑︎| Visual Studio | 1,2 GB | - 16 MB | - 44 MB | -60 MB | -5%
 | | | | | | 
= | 2 of 3 apps | 1,2 GB | - 28 MB | 66,3 MB | - 82,3 MB | 6,3%

**Comment by IngmarStein** [comment]
Monolingual does not do a preflight to estimate the space savings. I recommend CleanMyMac, if you need this.

**Comment by alpercoskun** [comment]
> I don't have an M1-based Mac to test, so I would appreciated if someone could test [22283e3](https://github.com/IngmarStein/Monolingual/commit/22283e37c1e63869ff70ea39774ae70306a34b11) and provide feedback here.
> 
> As for oneshot vs. automated operation: Monolingual is currently a manual operation, but you may have some luck automating it using the embedded command-line interface provided by the helper tool, see
> `/Applications/Monolingual.app/Contents/XPCServices/Monolingual.xpc/Contents/Library/LaunchServices/com.github.IngmarStein.Monolingual.Helper -h`

i have M1 mac mini, and I have Xcode 12.4... tried to compile, but is there any documentation for it ? when i tried it from command line w/ "make release", i got below error:

`bundle exec fastlane release
[✔] 🚀 
[14:03:10]: loading manifest: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/swift/upgrade_manifest.json
[14:03:10]: FastlaneSwiftRunner project is up-to-date
[14:03:11]: $ ./fastlane/FastlaneRunner lane release swiftServerPort 2000 > /dev/null
[14:03:11]: ▸ sh: line 1:  4970 Killed: 9               ./fastlane/FastlaneRunner lane release swiftServerPort 2000 > /dev/null
#<Thread:0x000000013296ea78@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane release swiftServerPort 2000 > /dev/null' was 137 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: line 1:  4970 Killed: 9               ./fastlane/FastlaneRunner lane release swiftServerPort 2000 > /dev/null
#<Thread:0x0000000132937f00@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
+-----------+---------+
|    Lane Context     |
+-----------+---------+
| LANE_NAME | release |
+-----------+---------+
[14:03:15]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
[14:03:15]: fastlane finished with errors

[!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
make: *** [deployment] Error 1
`

**Comment by IngmarStein** [comment]
Ah, codesigning of course… here's a build signed with my Developer ID: [Monolingual-1.8.2.dmg.zip](https://github.com/IngmarStein/Monolingual/files/6180654/Monolingual-1.8.2.dmg.zip)

**Comment by alpercoskun** [comment]
ok, it shows my architecture correctly: ARM64E. architecture list is also fine. but it doesn't remove anything. both on languages & arch window. on console, there is nothing helpful. let me know if i can help somehow to debug.

btw, on architecture section, Intel 64 is selected by default, but as you know, lots of apps doesn't support ARM currently, so we need Intel 64 too on M1 machines.

**Comment by IngmarStein** [comment]
A console log would be helpful, thanks!
It should be fine to select Intel64: Monolingual should only remove it when there is an ARM slice present - it would not be removed it if is the only architecture in a binary. This logic had been working in the PPC -> Intel transition, so it should be validated if it's still correct.

**Comment by alpercoskun** [comment]
[Monolingual.log](https://github.com/IngmarStein/Monolingual/files/6181827/Monolingual.log)

it is interesting, i clicked "remove" on both language and arch with default settings... but nothing happened...

**Comment by IngmarStein** [comment]
I didn't get much out of the attached log above. Was anything written to ~/Library/Logs/Monolingual.log?

Here's another build where I bumped the version number to 1.9.0 to ensure that the helper is updated (it is left alone if the version number doesn't change): [Monolingual-1.9.0.dmg.zip](https://github.com/IngmarStein/Monolingual/files/6185679/Monolingual-1.9.0.dmg.zip)

**Comment by alpercoskun** [comment]
uninstalled old file (w/ AppCleaner), installed Monolingual 1.9.0. after it i tried to delete languages & archs again, nothing happened.

this is ~/Library/Logs/Monolingual.log:
[Monolingual.log](https://github.com/IngmarStein/Monolingual/files/6185691/Monolingual.log)

**Comment by alpercoskun** [comment]
just to update about latest situation: macos 11.3 didn't solve the problem. it doesn't remove any files again. it has "full disk access" too. let me know if i can help somehow. maybe a test build with more debug lines can help, just my 2 cents.

**Comment by hacker1024** [comment]
I have the same log on Monterey: Deleted files is blank, and the progress bar just bounces around.
